php:
  build: php
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links:
    - db

db:
  image: mysql:5.7
  volumes:
   - ./db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - MYSQL_DATABASE=intranet
